allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  less: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.38'
  - '@vue/compiler-dom@3.5.38'
  - '@vue/compiler-sfc@3.5.38'
  - '@vue/compiler-ssr@3.5.38'
  - '@vue/reactivity@3.5.38'
  - '@vue/runtime-core@3.5.38'
  - '@vue/runtime-dom@3.5.38'
  - '@vue/server-renderer@3.5.38'
  - '@vue/shared@3.5.38'
  - vue@3.5.38
overrides:
  vite: latest
