shellEmulator: true

trustPolicy: no-downgrade

packages:
  - ./

pnpm:
  overrides:
    vite: npm:rolldown-vite@latest

onlyBuiltDependencies:
  - '@parcel/watcher'
  - less
  - better-sqlite3
  - esbuild
