shellEmulator: true

trustPolicy: no-downgrade

packages:
  - ./

catalog: {}

catalogs:
  dev: {}

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - sharp
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
